on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - name: Add SHORT_SHA env property with commit short sha
      id: dd
      run: echo "SHORT_SHA=`echo ${{ github.event.head_commit.id }} | cut -c1-8`" >> $GITHUB_ENV
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        # For posting a rich message using Block Kit
        payload: |
          {
            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
            {
              "type": "header",
              "text": {
                 "type": "plain_text",
                 "text": ":robot_face: GitHub Action build result: ${{ job.status }}",
                 "emoji": true
               }
            },
            {
              "type": "section",
              "fields": [
                {
                  "type": "mrkdwn",
                  "text": "• *repository:* ${{ github.event.repository.full_name }}"
                },
                {
                  "type": "mrkdwn",
                  "text": "• *current branch:* ${{ env.BRANCH_NAME }}"
                },
               {
                  "type": "mrkdwn",
                  "text": "• *pusher:* ${{ github.event.pusher.name }}"
                },
               {
                  "type": "mrkdwn",
                  "text": "• *author:* ${{ github.event.head_commit.author.name }}"
                }
              ]
            },
            {
              "type": "section",
              "text": {
                  "type": "mrkdwn",
                  "text": "*message _<${{ github.event.pull_request.html_url || github.event.head_commit.url }}| # ${{ env.SHORT_SHA }}>_* ```${{ github.event.head_commit.message }}```"
                }
              }
            ]
           }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}        
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHO 
        BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
